 export const NewData =[
    {
        "id": 1,
        "plot": "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
        "year": 1994,
        "genre": "Drama",
        "title": "The Shawshank Redemption",
        "actors": "Tim Robbins , Morgan Freeman",
        "awards": "Nominated for 7 Oscars",
        "poster": "The_Shawshank_Redemption",
        "rating": 9.3,
        "country": "USA",
        "runtime": 142,
        "trailer": "https://example.com/shawshank_redemption_trailer.mp4",
        "website": "http://www.warnerbros.com/movies/shawshank-redemption",
        "director": "Frank Darabont",
        "language": "English",
        "boxOffice": "$28.3 million",
        "production": "Columbia Pictures"
    },
    {
        "id": 2,
        "plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "year": 1972,
        "genre": "Crime , Drama",
        "title": "The God father",
        "actors": "Marlon Brando , Al Pacino , James Caan",
        "awards": "Won 3 Oscars",
        "poster": "The_God_father",
        "rating": 9.2,
        "country": "USA",
        "runtime": 175,
        "trailer": "https://example.com/the_godfather_trailer.mp4",
        "website": "https://www.paramountmovies.com/movies/the-godfather",
        "director": "Francis Ford Coppola",
        "language": "English",
        "boxOffice": "$245.1 million",
        "production": "Paramount Pictures"
    },
    {
        "id": 3,
        "plot": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "year": 2008,
        "genre": "Action , Crime , Drama",
        "title": "The Dark Knight",
        "actors": "Christian Bale , Heath Ledger , Gary Oldman",
        "awards": "Won 2 Oscars",
        "poster": "The_Dark_Knight",
        "rating": 9,
        "country": "USA",
        "runtime": 152,
        "trailer": "https://example.com/the_dark_knight_trailer.mp4",
        "website": "https://www.warnerbros.com/movies/dark-knight",
        "director": "Christopher Nolan",
        "language": "English",
        "boxOffice": "$1.005 billion",
        "production": "Warner Bros. Pictures"
    },
    {
        "id": 4,
        "plot": "The lives of two mob hitmen, a boxer, a gangsters wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "year": 1994,
        "genre": "Crime , Drama",
        "title": "Pulp Fiction",
        "actors": "John Travolta , Uma Thurman , Samuel L. Jackson",
        "awards": "Won 1 Oscar",
        "poster": "Pulp_Fiction",
        "rating": 8.9,
        "country": "USA",
        "runtime": 154,
        "trailer": "https://example.com/pulp_fiction_trailer.mp4",
        "website": "https://www.miramax.com/movie/pulp-fiction",
        "director": "Quentin Tarantino",
        "language": "English",
        "boxOffice": "$213.9 million",
        "production": "Miramax Films"
    },
    {
        "id": 5,
        "plot": "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
        "year": 1994,
        "genre": "Drama , Romance",
        "title": "Forrest Gump",
        "actors": "Tom Hanks , Robin Wright , Gary Sinise",
        "awards": "Won 6 Oscars",
        "poster": "Forrest_Gump",
        "rating": 8.8,
        "country": "USA",
        "runtime": 142,
        "trailer": "https://example.com/forrest_gump_trailer.mp4",
        "website": "https://www.paramountmovies.com/movies/forrest-gump",
        "director": "Robert Zemeckis",
        "language": "English",
        "boxOffice": "$677.9 million",
        "production": "Paramount Pictures"
    }
]
